# This file contains instructions for the build server Travis
# The build is running on https://travis-ci.com/.
sudo: required
dist: trusty
language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm run build
jobs:
  include:
  - stage: lint and test all packages
    script:
    - npm run build
    - npm run lint
    - npm run test
  - stage: release mouse-dispatcher package
    if: tag IS present
    before_deploy:
    - cd dist/scion/mouse-dispatcher
    after_deploy:
    - cd ../../..
    deploy:
    - provider: npm
      email: scion.collaborator@gmail.com
      api_key:
        secure: "FbNdERSRydcm38qnM9XV2HRSYhh7yi33JJe5FUSITDwQh8PAHjmxC5yCvyHHg2WBq5bLBS54oeR8NwomcTQXFL0s8d4Pte32sHBVgNnZ34U1IJDQ6Eufy01dZZjtZNfyv+3CeWOKgHWB963aBbCnfTisN2C66FBLQ4cK1cUO7UaMPZ6ux1wjhtFtd/Isih4TYNCmMRYGYZO1cNO+Ua84dm0j3ko8Hwx68Er3Ce3isQKqHKtXA5d0bX4/bYZuiXwWZwM/QQ2YMCALy8XOSBoE8ObBqOUiutO9LCsGEcPP5LiuWp0D1uqSvajdRhlmoTL3TI3/qDoLtkphww70JYzgRI8HJRekzGvg/gNqJrCDDxz51LpHVrH95TFS+pb9yw/OeEnT6HTpk3C0wc1KUx04EP90bJg36do+eixir3bqQsVJnFMZaBCPGOEyNHsHEqJ5tyKtqVW7UQeyynZGpNXhK1QRS+SQmisLP8nlo6QFheSn965Ke7kYoGB2olasUo7YKJko70bK4kCJOCPdbFyRQUBWGxjdFaAk29a9ekSj6RrkhazjqlxtZAUK72FSlj8UzloJKLugsBfhWEGPqorprbhyeK3qZUUj3ammiu4VW057A2FASAsE9Y80yzrO+0dJeIsTjHC6zNIaQj3KxR7jJBLGe0pKMpql75Adne+ThZM="
      skip_cleanup: true
      on:
        tags: true
        condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+$" # Matches 'stable' versions x.x.x (npm tag: latest)
    - provider: npm
      tag: next
      email: scion.collaborator@gmail.com
      api_key:
        secure: "FbNdERSRydcm38qnM9XV2HRSYhh7yi33JJe5FUSITDwQh8PAHjmxC5yCvyHHg2WBq5bLBS54oeR8NwomcTQXFL0s8d4Pte32sHBVgNnZ34U1IJDQ6Eufy01dZZjtZNfyv+3CeWOKgHWB963aBbCnfTisN2C66FBLQ4cK1cUO7UaMPZ6ux1wjhtFtd/Isih4TYNCmMRYGYZO1cNO+Ua84dm0j3ko8Hwx68Er3Ce3isQKqHKtXA5d0bX4/bYZuiXwWZwM/QQ2YMCALy8XOSBoE8ObBqOUiutO9LCsGEcPP5LiuWp0D1uqSvajdRhlmoTL3TI3/qDoLtkphww70JYzgRI8HJRekzGvg/gNqJrCDDxz51LpHVrH95TFS+pb9yw/OeEnT6HTpk3C0wc1KUx04EP90bJg36do+eixir3bqQsVJnFMZaBCPGOEyNHsHEqJ5tyKtqVW7UQeyynZGpNXhK1QRS+SQmisLP8nlo6QFheSn965Ke7kYoGB2olasUo7YKJko70bK4kCJOCPdbFyRQUBWGxjdFaAk29a9ekSj6RrkhazjqlxtZAUK72FSlj8UzloJKLugsBfhWEGPqorprbhyeK3qZUUj3ammiu4VW057A2FASAsE9Y80yzrO+0dJeIsTjHC6zNIaQj3KxR7jJBLGe0pKMpql75Adne+ThZM="
      skip_cleanup: true
      on:
        tags: true
        condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+-" # Matches 'next' versions x.x.x-beta and x.x.x-rc (npm tag: next)
  - stage: release dimension package
    if: tag IS present
    before_deploy:
    - cd dist/scion/dimension
    after_deploy:
    - cd ../../..
    deploy:
    - provider: npm
      email: scion.collaborator@gmail.com
      api_key:
        secure: "FbNdERSRydcm38qnM9XV2HRSYhh7yi33JJe5FUSITDwQh8PAHjmxC5yCvyHHg2WBq5bLBS54oeR8NwomcTQXFL0s8d4Pte32sHBVgNnZ34U1IJDQ6Eufy01dZZjtZNfyv+3CeWOKgHWB963aBbCnfTisN2C66FBLQ4cK1cUO7UaMPZ6ux1wjhtFtd/Isih4TYNCmMRYGYZO1cNO+Ua84dm0j3ko8Hwx68Er3Ce3isQKqHKtXA5d0bX4/bYZuiXwWZwM/QQ2YMCALy8XOSBoE8ObBqOUiutO9LCsGEcPP5LiuWp0D1uqSvajdRhlmoTL3TI3/qDoLtkphww70JYzgRI8HJRekzGvg/gNqJrCDDxz51LpHVrH95TFS+pb9yw/OeEnT6HTpk3C0wc1KUx04EP90bJg36do+eixir3bqQsVJnFMZaBCPGOEyNHsHEqJ5tyKtqVW7UQeyynZGpNXhK1QRS+SQmisLP8nlo6QFheSn965Ke7kYoGB2olasUo7YKJko70bK4kCJOCPdbFyRQUBWGxjdFaAk29a9ekSj6RrkhazjqlxtZAUK72FSlj8UzloJKLugsBfhWEGPqorprbhyeK3qZUUj3ammiu4VW057A2FASAsE9Y80yzrO+0dJeIsTjHC6zNIaQj3KxR7jJBLGe0pKMpql75Adne+ThZM="
      skip_cleanup: true
      on:
        tags: true
        condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+$" # Matches 'stable' versions x.x.x (npm tag: latest)
    - provider: npm
      tag: next
      email: scion.collaborator@gmail.com
      api_key:
        secure: "FbNdERSRydcm38qnM9XV2HRSYhh7yi33JJe5FUSITDwQh8PAHjmxC5yCvyHHg2WBq5bLBS54oeR8NwomcTQXFL0s8d4Pte32sHBVgNnZ34U1IJDQ6Eufy01dZZjtZNfyv+3CeWOKgHWB963aBbCnfTisN2C66FBLQ4cK1cUO7UaMPZ6ux1wjhtFtd/Isih4TYNCmMRYGYZO1cNO+Ua84dm0j3ko8Hwx68Er3Ce3isQKqHKtXA5d0bX4/bYZuiXwWZwM/QQ2YMCALy8XOSBoE8ObBqOUiutO9LCsGEcPP5LiuWp0D1uqSvajdRhlmoTL3TI3/qDoLtkphww70JYzgRI8HJRekzGvg/gNqJrCDDxz51LpHVrH95TFS+pb9yw/OeEnT6HTpk3C0wc1KUx04EP90bJg36do+eixir3bqQsVJnFMZaBCPGOEyNHsHEqJ5tyKtqVW7UQeyynZGpNXhK1QRS+SQmisLP8nlo6QFheSn965Ke7kYoGB2olasUo7YKJko70bK4kCJOCPdbFyRQUBWGxjdFaAk29a9ekSj6RrkhazjqlxtZAUK72FSlj8UzloJKLugsBfhWEGPqorprbhyeK3qZUUj3ammiu4VW057A2FASAsE9Y80yzrO+0dJeIsTjHC6zNIaQj3KxR7jJBLGe0pKMpql75Adne+ThZM="
      skip_cleanup: true
      on:
        tags: true
        condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+-" # Matches 'next' versions x.x.x-beta and x.x.x-rc (npm tag: next)
  - stage: release viewport package
    if: tag IS present
    before_deploy:
    - cd dist/scion/viewport
    after_deploy:
    - cd ../../..
    deploy:
    - provider: npm
      email: scion.collaborator@gmail.com
      api_key:
        secure: "FbNdERSRydcm38qnM9XV2HRSYhh7yi33JJe5FUSITDwQh8PAHjmxC5yCvyHHg2WBq5bLBS54oeR8NwomcTQXFL0s8d4Pte32sHBVgNnZ34U1IJDQ6Eufy01dZZjtZNfyv+3CeWOKgHWB963aBbCnfTisN2C66FBLQ4cK1cUO7UaMPZ6ux1wjhtFtd/Isih4TYNCmMRYGYZO1cNO+Ua84dm0j3ko8Hwx68Er3Ce3isQKqHKtXA5d0bX4/bYZuiXwWZwM/QQ2YMCALy8XOSBoE8ObBqOUiutO9LCsGEcPP5LiuWp0D1uqSvajdRhlmoTL3TI3/qDoLtkphww70JYzgRI8HJRekzGvg/gNqJrCDDxz51LpHVrH95TFS+pb9yw/OeEnT6HTpk3C0wc1KUx04EP90bJg36do+eixir3bqQsVJnFMZaBCPGOEyNHsHEqJ5tyKtqVW7UQeyynZGpNXhK1QRS+SQmisLP8nlo6QFheSn965Ke7kYoGB2olasUo7YKJko70bK4kCJOCPdbFyRQUBWGxjdFaAk29a9ekSj6RrkhazjqlxtZAUK72FSlj8UzloJKLugsBfhWEGPqorprbhyeK3qZUUj3ammiu4VW057A2FASAsE9Y80yzrO+0dJeIsTjHC6zNIaQj3KxR7jJBLGe0pKMpql75Adne+ThZM="
      skip_cleanup: true
      on:
        tags: true
        condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+$" # Matches 'stable' versions x.x.x (npm tag: latest)
    - provider: npm
      tag: next
      email: scion.collaborator@gmail.com
      api_key:
        secure: "FbNdERSRydcm38qnM9XV2HRSYhh7yi33JJe5FUSITDwQh8PAHjmxC5yCvyHHg2WBq5bLBS54oeR8NwomcTQXFL0s8d4Pte32sHBVgNnZ34U1IJDQ6Eufy01dZZjtZNfyv+3CeWOKgHWB963aBbCnfTisN2C66FBLQ4cK1cUO7UaMPZ6ux1wjhtFtd/Isih4TYNCmMRYGYZO1cNO+Ua84dm0j3ko8Hwx68Er3Ce3isQKqHKtXA5d0bX4/bYZuiXwWZwM/QQ2YMCALy8XOSBoE8ObBqOUiutO9LCsGEcPP5LiuWp0D1uqSvajdRhlmoTL3TI3/qDoLtkphww70JYzgRI8HJRekzGvg/gNqJrCDDxz51LpHVrH95TFS+pb9yw/OeEnT6HTpk3C0wc1KUx04EP90bJg36do+eixir3bqQsVJnFMZaBCPGOEyNHsHEqJ5tyKtqVW7UQeyynZGpNXhK1QRS+SQmisLP8nlo6QFheSn965Ke7kYoGB2olasUo7YKJko70bK4kCJOCPdbFyRQUBWGxjdFaAk29a9ekSj6RrkhazjqlxtZAUK72FSlj8UzloJKLugsBfhWEGPqorprbhyeK3qZUUj3ammiu4VW057A2FASAsE9Y80yzrO+0dJeIsTjHC6zNIaQj3KxR7jJBLGe0pKMpql75Adne+ThZM="
      skip_cleanup: true
      on:
        tags: true
        condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+-" # Matches 'next' versions x.x.x-beta and x.x.x-rc (npm tag: next)
  - stage: release workbench package
    if: tag IS present
    before_deploy:
    - cd dist/scion/workbench
    after_deploy:
    - cd ../../..
    deploy:
    - provider: npm
      email: scion.collaborator@gmail.com
      api_key:
        secure: "FbNdERSRydcm38qnM9XV2HRSYhh7yi33JJe5FUSITDwQh8PAHjmxC5yCvyHHg2WBq5bLBS54oeR8NwomcTQXFL0s8d4Pte32sHBVgNnZ34U1IJDQ6Eufy01dZZjtZNfyv+3CeWOKgHWB963aBbCnfTisN2C66FBLQ4cK1cUO7UaMPZ6ux1wjhtFtd/Isih4TYNCmMRYGYZO1cNO+Ua84dm0j3ko8Hwx68Er3Ce3isQKqHKtXA5d0bX4/bYZuiXwWZwM/QQ2YMCALy8XOSBoE8ObBqOUiutO9LCsGEcPP5LiuWp0D1uqSvajdRhlmoTL3TI3/qDoLtkphww70JYzgRI8HJRekzGvg/gNqJrCDDxz51LpHVrH95TFS+pb9yw/OeEnT6HTpk3C0wc1KUx04EP90bJg36do+eixir3bqQsVJnFMZaBCPGOEyNHsHEqJ5tyKtqVW7UQeyynZGpNXhK1QRS+SQmisLP8nlo6QFheSn965Ke7kYoGB2olasUo7YKJko70bK4kCJOCPdbFyRQUBWGxjdFaAk29a9ekSj6RrkhazjqlxtZAUK72FSlj8UzloJKLugsBfhWEGPqorprbhyeK3qZUUj3ammiu4VW057A2FASAsE9Y80yzrO+0dJeIsTjHC6zNIaQj3KxR7jJBLGe0pKMpql75Adne+ThZM="
      skip_cleanup: true
      on:
        tags: true
        condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+$" # Matches 'stable' versions x.x.x (npm tag: latest)
    - provider: npm
      tag: next
      email: scion.collaborator@gmail.com
      api_key:
        secure: "FbNdERSRydcm38qnM9XV2HRSYhh7yi33JJe5FUSITDwQh8PAHjmxC5yCvyHHg2WBq5bLBS54oeR8NwomcTQXFL0s8d4Pte32sHBVgNnZ34U1IJDQ6Eufy01dZZjtZNfyv+3CeWOKgHWB963aBbCnfTisN2C66FBLQ4cK1cUO7UaMPZ6ux1wjhtFtd/Isih4TYNCmMRYGYZO1cNO+Ua84dm0j3ko8Hwx68Er3Ce3isQKqHKtXA5d0bX4/bYZuiXwWZwM/QQ2YMCALy8XOSBoE8ObBqOUiutO9LCsGEcPP5LiuWp0D1uqSvajdRhlmoTL3TI3/qDoLtkphww70JYzgRI8HJRekzGvg/gNqJrCDDxz51LpHVrH95TFS+pb9yw/OeEnT6HTpk3C0wc1KUx04EP90bJg36do+eixir3bqQsVJnFMZaBCPGOEyNHsHEqJ5tyKtqVW7UQeyynZGpNXhK1QRS+SQmisLP8nlo6QFheSn965Ke7kYoGB2olasUo7YKJko70bK4kCJOCPdbFyRQUBWGxjdFaAk29a9ekSj6RrkhazjqlxtZAUK72FSlj8UzloJKLugsBfhWEGPqorprbhyeK3qZUUj3ammiu4VW057A2FASAsE9Y80yzrO+0dJeIsTjHC6zNIaQj3KxR7jJBLGe0pKMpql75Adne+ThZM="
      skip_cleanup: true
      on:
        tags: true
        condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+-" # Matches 'next' versions x.x.x-beta and x.x.x-rc (npm tag: next)
