# This file contains instructions for the build server Travis
# The build is running on https://travis-ci.com/.

sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - ng lint @scion/workbench
  - ng test @scion/workbench --watch=false
  - ng build @scion/workbench --prod
