name: Publish TypeDoc for @scion/workbench-client
on: workflow_dispatch
env:
  NODE_VERSION: 20.14.0
jobs:
  install:
    name: 'Installing NPM modules'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'Caching NPM modules if necessary'
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: ./node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci
  publish-typedoc:
    name: 'Publishing TypeDoc'
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'Restoring NPM modules from cache'
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: 'Reading package.json version of scion/workbench-client'
        uses: SchweizerischeBundesbahnen/scion-toolkit/.github/actions/package-json@master
        id: workbench-client-package-json
        with:
          path: projects/scion/workbench-client/package.json
      - name: 'Building TypeDoc for @scion/workbench-client'
        run: npm run workbench-client:typedoc
      - name: 'Publishing TypeDoc for @scion/workbench-client to Vercel'
        uses: SchweizerischeBundesbahnen/scion-toolkit/.github/actions/vercel-deploy@master
        with:
          dist-folder: dist/workbench-client-api
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          project-id: ${{ secrets.VERCEL_WORKBENCH_CLIENT_API_PROJECT_ID }}
          version: ${{ steps.workbench-client-package-json.outputs.version }}
          aliases: |
            workbench-client-api.scion.vercel.app,
            workbench-client-api-v%v.scion.vercel.app
